import React, { useEffect } from "react";

const LEGAL_DOCUMENTS = {
  "Privacy Policy": {
    title: "PRIVACY POLICY & DATA HANDLING",
    content: (
      <div className="space-y-4">
        <p><strong>EFFECTIVE DATE:</strong> 01 JAN 2026</p>
        <p>
          Trishul Dynamics Pvt. Ltd. ("Company", "we", "our") is committed to protecting the privacy and security of all operational and personal data. This policy applies to visitors of the AEROS MK-1 information portal and any subsequent digital interactions.
        </p>
        <h3 className="text-amber-400 font-bold mt-4">1. DATA COLLECTION</h3>
        <p>
          As a defence-oriented platform, this website does not deploy standard third-party tracking cookies for advertising purposes. We collect minimal telemetry data (IP address, user agent, timestamp) strictly for security monitoring and threat mitigation.
        </p>
        <h3 className="text-amber-400 font-bold mt-4">2. TELEMETRY & HARDWARE DATA</h3>
        <p>
          Data generated by AEROS MK-1 units during field trials or operations-including but not limited to GPS tracks, thermal imagery, LiDAR point clouds, and RF telemetry-are strictly governed by the Ministry of Defence (MoD) data residency policies. None of this operational data is processed, stored, or accessible via this public-facing website.
        </p>
        <h3 className="text-amber-400 font-bold mt-4">3. DATA RETENTION & SHARING</h3>
        <p>
          We do not sell, lease, or distribute visitor information. Information submitted via contact forms is securely transmitted to our internal procurement servers and is subject to Indian IT Act (2000) and DPDP Act compliance.
        </p>
      </div>
    )
  },
  "NDA Template": {
    title: "MUTUAL NON-DISCLOSURE AGREEMENT (PREVIEW)",
    content: (
      <div className="space-y-4 text-sm">
        <p className="text-amber-500/80 mb-4 border border-amber-500/20 p-3 bg-amber-500/5">
          NOTE: This is a restricted preview of the Trishul Dynamics Mutual NDA. A digitally signed copy is required before accessing CAD files, RF architecture, or conducting physical site evaluations.
        </p>
        <p><strong>1. PURPOSE:</strong> The parties intend to engage in discussions regarding the evaluation, procurement, or integration of the AEROS MK-1 UAV/UGV platform ("Purpose").</p>
        <p><strong>2. CONFIDENTIAL INFORMATION:</strong> Includes, without limitation, technical specifications, kinematic mechanisms, source code, payload integration protocols, pricing structures, and test flight telemetry.</p>
        <p><strong>3. OBLIGATIONS:</strong> The Receiving Party shall maintain the Confidential Information in strict confidence and use it solely for the Purpose. It shall not be disclosed to any third party without prior written consent, except to employees or government officials on a strict "need-to-know" basis.</p>
        <p><strong>4. EXCLUSIONS:</strong> Information that is publicly known, already in possession of the Receiving Party, or independently developed without reference to the Confidential Information is excluded.</p>
        <p><strong>5. GOVERNING LAW:</strong> This Agreement shall be governed by the laws of India, subject to the exclusive jurisdiction of the courts in Delhi.</p>
      </div>
    )
  },
  "Terms of Use": {
    title: "WEBSITE TERMS OF USE",
    content: (
      <div className="space-y-4">
        <p>
          By accessing the Trishul Dynamics AEROS MK-1 portal, you agree to comply with these terms. This website is intended solely for informational purposes regarding our defence and aerospace capabilities.
        </p>
        <h3 className="text-amber-400 font-bold mt-4">1. INTELLECTUAL PROPERTY</h3>
        <p>
          All content, including the morphing kinematic mechanism diagrams, branding, images, and text, are the exclusive intellectual property of Trishul Dynamics Pvt. Ltd. and are protected by Indian and international copyright and patent laws.
        </p>
        <h3 className="text-amber-400 font-bold mt-4">2. NO WARRANTIES</h3>
        <p>
          The specifications and performance metrics provided (e.g., endurance, range, AI latency) are based on prototype testing and simulated environments. Final production parameters may vary based on specific military requirements and payload configurations.
        </p>
        <h3 className="text-amber-400 font-bold mt-4">3. RESTRICTION OF ACCESS</h3>
        <p>
          We reserve the right to monitor access to this portal and block IP addresses exhibiting malicious scraping, unauthorized vulnerability scanning, or other hostile cyber activities.
        </p>
      </div>
    )
  },
  "Export Control Notice": {
    title: "ITAR / SCOMET EXPORT CONTROL NOTICE",
    content: (
      <div className="space-y-4">
        <div className="border-l-2 border-red-500 pl-4 py-2 bg-red-500/5 text-red-400 font-mono text-sm mb-4">
          WARNING: RESTRICTED DEFENCE ARTICLE
        </div>
        <p>
          The AEROS MK-1 and its associated sub-systems (including the flight controller, RF communication modules, thermal payloads, and Edge AI tracking software) are classified as dual-use and military goods.
        </p>
        <p>
          <strong>SCOMET COMPLIANCE:</strong> Export of these systems from India is strictly governed by the Directorate General of Foreign Trade (DGFT) under the Special Chemicals, Organisms, Materials, Equipment and Technologies (SCOMET) list (Category 8: UAVs and Munitions).
        </p>
        <p>
          <strong>NO UNAUTHORISED TRANSFER:</strong> Technical data provided on this portal may not be exported, re-exported, or transferred to foreign nationals or entities outside of India without prior authorisation from the Ministry of Defence (MoD) and DGFT.
        </p>
      </div>
    )
  },
  "Responsible Disclosure": {
    title: "RESPONSIBLE DISCLOSURE PROGRAM",
    content: (
      <div className="space-y-4">
        <p>
          Trishul Dynamics takes the security of our platforms and digital infrastructure seriously. We encourage the cybersecurity community to report potential vulnerabilities in our web portal or public-facing APIs in a responsible manner.
        </p>
        <h3 className="text-teal-300 font-bold mt-4">SCOPE & RULES OF ENGAGEMENT</h3>
        <ul className="list-disc pl-5 space-y-2 text-slate-300">
          <li><strong>In Scope:</strong> The trishuldynamics.com web domain and its subdomains.</li>
          <li><strong>Out of Scope:</strong> Any physical hardware, RF links (ExpressLRS/MAVLink), ground control stations, or proprietary flight controller firmware. Attempting to exploit these systems without authorization is a violation of the IT Act and will be prosecuted.</li>
          <li><strong>No Disruption:</strong> Do not use automated scanners that generate significant traffic or attempt Denial of Service (DoS) attacks.</li>
        </ul>
        <p className="mt-4">
          <strong>REPORTING:</strong> Please submit findings via encrypted email to <code>security@trishuldynamics.com</code>. We aim to acknowledge receipt within 48 hours.
        </p>
      </div>
    )
  }
};

export default function LegalModal({ isOpen, onClose, docType }) {
  // Prevent body scrolling when modal is open
  useEffect(() => {
    if (isOpen) {
      document.body.style.overflow = "hidden";
    } else {
      document.body.style.overflow = "unset";
    }
    return () => {
      document.body.style.overflow = "unset";
    };
  }, [isOpen]);

  if (!isOpen || !docType || !LEGAL_DOCUMENTS[docType]) return null;

  const doc = LEGAL_DOCUMENTS[docType];

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center p-4 sm:p-6">
      {/* Backdrop */}
      <div 
        className="absolute inset-0 bg-[#020205]/80 backdrop-blur-sm"
        onClick={onClose}
      />
      
      {/* Modal Container */}
      <div className="relative w-full max-w-3xl bg-[#09090f] border border-amber-500/20 shadow-2xl flex flex-col max-h-[85vh] animate-fade-in-up">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-amber-500/10 p-5 bg-[#0e0e1a]">
          <div className="flex items-center gap-3">
            <span className="w-2 h-2 rounded-full bg-amber-500 animate-pulse" />
            <h2 className="font-mono text-sm tracking-widest text-white">
              {doc.title}
            </h2>
          </div>
          <button 
            onClick={onClose}
            className="text-slate-500 hover:text-amber-400 transition-colors p-1"
          >
            <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
              <line x1="18" y1="6" x2="6" y2="18"></line>
              <line x1="6" y1="6" x2="18" y2="18"></line>
            </svg>
          </button>
        </div>

        {/* Content Body */}
        <div className="p-6 overflow-y-auto text-slate-400 text-sm leading-relaxed custom-scrollbar">
          {doc.content}
        </div>

        {/* Footer */}
        <div className="border-t border-amber-500/10 p-4 bg-[#0a0a14] flex justify-between items-center">
          <div className="font-mono text-[9px] text-slate-600 tracking-widest">
            TRISHUL DYNAMICS INTERNAL · DOCUMENT CLASSIFICATION: PUBLIC
          </div>
          <button 
            onClick={onClose}
            className="px-4 py-2 border border-slate-700 text-slate-400 font-mono text-[10px] tracking-widest hover:bg-slate-800 hover:text-white transition-colors"
          >
            ACKNOWLEDGE & CLOSE
          </button>
        </div>
      </div>
    </div>
  );
}
